### PR TITLE
#165020216 Add pagination

### PR DESCRIPTION
**Pull request by fridolinho**
## What does this PR do?
Add pagination functionnality
## Description of Task to be completed?
- write test
- update query using offset and limit parameters
## How should this be manually tested?
1. Run these commands
     - clone https://github.com/andela/ah-kgl-avengers-backend.git
     - git checkout ft-user-functionality-165020217
     - npm install
     - npm test
2. [check travis build here](https://travis-ci.com/andela/ah-kgl-avengers-backend/builds/109708533)
3. Postman
     - send a get request on localhost:3000/api/v1/articles?limit=x&offset=y
         x is a variable and represent the number of articles that will returned.
         y is a variable that represent the number of articles that will be skipped

## What are the relevant pivotal tracker stories?
[Add pagination #165020216](https://www.pivotaltracker.com/story/show/165020216)
## Screenshots (if appropriate)
image

### CODE REVIEW

**Review by aaronsekisambu — CHANGES_REQUESTED** [review]
@fridolinho please update the PR name to the acceptable naming conversion

**Review by aaronsekisambu — DISMISSED** [review]

**Review by aaronsekisambu — DISMISSED** [review]

**Review by niyobobo — DISMISSED** [review]
LGTM

**Review by shemaeric — DISMISSED** [review]
LGTM

**Review by avpaul — DISMISSED** [review]
Works as expected

**Review by avpaul — APPROVED** [review]

**Review by niyobobo — APPROVED** [review]
Nice to fix the conflicts. now it looks good.

**Review by daud1 — APPROVED** [review]
LGTM

**Pull request merged**
