### PR TITLE
#166889863 add the total count for dislikes

### PR DESCRIPTION
**Pull request by shemaeric**
## What does this PR do?
This PR adds the total count for the number of dislikes that article has on its object.
## Description of Task to be completed?
- Add the count on the article object after a user has disliked an article
## How should this be manually tested?
- Clone the repo `https://github.com/andela/ah-kgl-avengers-backend`
- Checkout to the branch `ch-add-dislike-count-166889863`
- Run `npm install` and also `npm start`
- To test the return of dislike articles try to dislike an article through this endpoint `localhost:3000/api/v1/articles/:slug/dislike` then get articles again through `localhost:3000/api/v1/articles/`, you will get a response object which has an article object that contains dislikes as number of counts.
## Any background context you want to provide?
- You need to be logged in
- You need to have an article created and also published.
## What are the relevant pivotal tracker stories?
[166889863](https://www.pivotaltracker.com/n/projects/2321840)
## Screenshots (if appropriate)
Screen Shot 2019-06-25 at 02 55 06

## Questions:

None

### CODE REVIEW

**Comment by avpaul** [comment]
@shemaeric Can you change the PR title?

**Review by avpaul — DISMISSED** [review]

**Review by fridolinho — DISMISSED** [review]
LGTM

**Review by niyobobo — DISMISSED** [review]
LGTM

**Review by aaronsekisambu — APPROVED** [review]

**Review by niyobobo — APPROVED** [review]

**Review by avpaul — APPROVED** [review]

**Review by fridolinho — APPROVED** [review]
Looks Good to me

**Pull request merged**
