### PR TITLE
#166114900 refactor getting users

### PR DESCRIPTION
**Pull request by fridolinho**
## What does this PR do?
Refactor getting users
## Description of Task to be completed?
- removed the endpoint of getting all authors
- updated getting all users to accept pagination
- accept only super admin to access the endpoint
## How should this be manually tested?
     - clone https://github.com/andela/ah-kgl-avengers-backend.git
     - git checkout ch-getting-users-166114900
     - get Users using a post request on localhost:3000/api/v1/users
    N.B: User should super admin, otherwise he is not authorised to access the endpoint.

## Any background context you want to provide?
N/A
## What are the relevant pivotal tracker stories?
[getting users](https://www.pivotaltracker.com/story/show/166114900)
## Screenshots (if appropriate)
image

## Questions:
N/A

### CODE REVIEW

**Review by avpaul — APPROVED** [review]
LGTM 💯

**Review by niyobobo — APPROVED** [review]
Thanks, @fridolinho for code refactoring. (Removing the useless endpoint)

LGTM

**Review by aaronsekisambu — APPROVED** [review]
Working as expected

**Review by shemaeric — APPROVED** [review]
LGTM, that's a good job

**Pull request merged**
