### PR TITLE
#165020189 Integration of TravisCI

### PR DESCRIPTION
**Pull request by niyobobo**
## What does this PR do?
Integrating TravisCI in the project and add build badge on the README file 
 ## Description of Task to be completed?
- Added .travis.yml file for TravisCI configuration as the test server.
- Added build badge to the README file
- Added PR Description markdown Template  file
 ## How should this be manually tested?
- The badge on the README file
- [Build server](https://travis-ci.com/andela/ah-kgl-avengers-backend)
 ## Any background context you want to provide?
TravisCI badge will start showing the build status after this PR merged into develop branch
 ## What are the relevant pivotal tracker stories?
[#165020189](https://www.pivotaltracker.com/n/projects/2321840)
 ## Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by fridolinho** [comment]
good work

**Review by fridolinho — COMMENTED** [review]
Job wel done!

**Review by daud1 — CHANGES_REQUESTED** [review]
LGTM
However, you need to resolve the merge conflicts that you have in the package-lock.json
To do that:
- Pull the latest changes from develop
- Rebase your branch to develop
- Delete the package-lock.json
- Regenerate the package-lock using `npm install`

**Comment by niyobobo** [comment]
> LGTM
> However, you need to resolve the merge conflicts that you have in the package-lock.json
> To do that:
> 
> * Pull the latest changes from develop
> * Rebase your branch to develop
> * Delete the package-lock.json
> * Regenerate the package-lock using `npm install`

The Change conflict now solved

**Review by avpaul — APPROVED** [review]

**Review by daud1 — APPROVED** [review]

**Pull request merged**
