### PR TITLE
#166903228 User should be able to update profile info

### PR DESCRIPTION
**Pull request by avpaul**
## What does this PR do?
- Refactor profile endpoints 

## Description of Task to be completed?
- Refactor get profile endpoints to return email, last/first names
- Update user first/last names
- Remove backend picture manipulation (Images will be uploaded to Cloudinary on the front end)

## How should this be manually tested?
Run the following code 
```sh
git pull origin
git checkout ch-fix-profile-endpoints-166903228
npm install
npm start
```
### Postman
-  login to get a token then follow steps shown in the image 
Screen Shot 2019-06-25 at 17 38 14

### CLI Tests 
```sh
npm run test:all
```

## Any background context you want to provide?
- We need first/last names on the user profile page on the front end

## What are the relevant pivotal tracker stories?
[User should be bale to update his/her names #43 166903228](https://www.pivotaltracker.com/n/projects/2321840/stories/166903228)

## Screenshots 
Screen Shot 2019-06-25 at 16 52 53

## Questions:
None

### CODE REVIEW

**Review by fridolinho — DISMISSED** [review]
LGTM

**Review by niyobobo — DISMISSED** [review]

**Review by shemaeric — APPROVED** [review]
Looks Good after everything fixed.

**Review by niyobobo — APPROVED** [review]

**Review by fridolinho — APPROVED** [review]
It is finally okay

**Review by aaronsekisambu — APPROVED** [review]
Apart from the test failing. The PR is working as expected.

**Pull request merged**
